### PR TITLE
Updated configs for a ton of maps

### PR DESCRIPTION
**Pull request by Koi-TF2**
This commit adds support for

cp_glassworks_rc6a.cfg
cp_kalinka_rc6a.cfg
cp_mist_rc1e.cfg
cp_process_f9a.cfg
cp_prolands_rc2ta.cfg
cp_propaganda_b19.cfg
cp_villa_b18.cfg
ctf_turbine_pro_rc4.cfg
koth_ashville_rc2d.cfg
koth_bagel_rc4a.cfg
koth_bagel_rc5.cfg
koth_berryville_b1a.cfg
koth_berryville_b2a.cfg
koth_cascade.cfg
koth_lakeside_r2.cfg
koth_warmtic_f9.cfg
pl_borneo_f1.cfg
pl_cornwater_b7c_fix.cfg
pl_summercoast_rc8e.cfg
pl_upward_f5.cfg
pl_vigil_rc9.cfg

I scrapped my previous config directory re-structure so all the config files remain in the same dir now. A few spawns were fixed on glassworks, kalinka, warmtic, cornwater, borneo that got people stuck in the floor or wall. All configs based on previous map version configs. A handful have been cleaned up by rounding to nearest integer, correctly mirroring the corresponding opposite-side spawns, and also naming some of the spawns

### CODE REVIEW

**Comment by Koi-TF2** [comment]
ok yeah that title is too long lol

**Comment by sapphonie** [comment]
nitpick, make sure these files have newlines at the end of them please, other than that lgtm

**Comment by Koi-TF2** [comment]
> nitpick, make sure these files have newlines at the end of them please, other than that lgtm

Changed them all to include a newline as requested, should be all set now. Thanks


Double standards though - see https://github.com/sapphonie/SOAP-TF2DM/pull/25/files and https://github.com/sapphonie/SOAP-TF2DM/pull/23/files

**Comment by sapphonie** [comment]
> Double standards though 

true. i need to setup an .editorconfig for this repo at some point. anyway lgtm

**Pull request merged**
