### PR TITLE
Cleanup ru translation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by sapphonie** [comment]
denied, those are not language dependent, they are part of sourcemod's translation process

https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)

**Comment by Blueberryy** [comment]
bruh. if en translation have it will use formats from them

**Comment by Blueberryy** [comment]
so you don't have to add formats in every translation file. only in one :p

**Comment by sapphonie** [comment]
yup i'm wrong. merged

**Pull request merged**
